version: "3.9"

services:
  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis-exporter:
    container_name: redis-exporter-container
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      REDIS_ADDR: "redis://:${REDIS_PASSWORD}@redis:6379"
    depends_on:
      redis:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
      - "61613:61613"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_stomp rabbitmq_web_stomp rabbitmq_prometheus &&
             rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 5s
      timeout: 5s
      retries: 10

  prometheus:
    container_name: prometheus-container
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - app-network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml.template"
      - "--storage.tsdb.path=/prometheus"

  grafana:
    container_name: grafana-container
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus

  nginx:
    container_name: nginx-container
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
